from typing import Protocol

class TemperatureSensor(Protocol):
    def get_temperature(self) -> float: ...

class PressureSensor(Protocol):
    def get_pressure(self) -> float: ...

class HumiditySensor(Protocol):
    def get_humidity(self) -> float: ...

class LightSensor(Protocol):
    def get_light(self) -> float: ...

class MicrophoneSensor(Protocol):
    def get_sound_level(self) -> float: ...

class ParticulateMatterSensor(Protocol):
    def get_particulate_matter(self) -> dict: ...

class Co2Sensor(Protocol):
    def get_co2(self) -> float: ...