from typing import Protocol

class TemperatureSensor(Protocol):
    def get_temperature(self) -> float: ...
    def get_average_temperature(self) -> float: ...

class PressureSensor(Protocol):
    def get_pressure(self) -> float: ...
    def get_average_pressure(self) -> float: ...

class HumiditySensor(Protocol):
    def get_humidity(self) -> float: ...
    def get_average_humidity(self) -> float: ...

class LightSensor(Protocol):
    def get_light(self) -> float: ...
    def get_average_light(self) -> float: ...

class MicrophoneSensor(Protocol):
    def get_sound_level(self) -> float: ...
    def get_average_sound_level(self) -> float: ...

class ParticulateMatterSensor(Protocol):
    def get_particulate_matter(self) -> dict: ...
    def get_average_particulate_matter(self) -> dict: ...

class Co2Sensor(Protocol):
    def get_co2(self) -> float: ...
    def get_average_co2(self) -> float: ...